#!/bin/sh

set -e

case $1 in
  configure)
    mkdir -p /var/run/stud
    ;;
esac

if service stud status >/dev/null 2>&1; then
  echo
  echo "              !!!! WARNING !!!!"
  echo
  echo "stud is running, you should restart it."
  echo
fi

#DEBHELPER#

exit 0

# EOF
